#+TITLE: Newmacs config

A modular Emacs config made for easy and flexible end-user configuration.

It is separated into different modules, separated by file.

Designed with speed, modularity, and minimalism in mind, it makes reducing your config to only the bare minimum easy.

This project is still very incomplete and under active development.

* Installation

To use this config without eradicating your pre-existing =~/.emacs.d=, you may git clone the project anywhere, and then run =$ emacs --init-directory <path-to-configdir>= to run emacs from that directory. 
Because meow with dvorak-programmer is the default, run the previous command with the argument =--sane-keybinds= to load qwerty meow keybinds.

All this is subject to change.

* Configuration

You can configure which modules are loaded in =config.el=. However, I wouldn't advise configuring it and expecting everything to work when you next git pull.

* TODO:
- [ ] able to swap between evil and meow
- [ ] try to make compatible with at least dvp and qwerty
- [ ] evil-mode
- [ ] undo-tree
- [ ] crux
- [ ] free-keys
- [ ] better window management
- [ ] ivy config
- [ ] better ivy
- [ ] info
- [ ] darkroom
- [ ] calc
- [ ] dired/dirvish improve keybinds
- [ ] improve keybinds for everything
- [ ] stumpwm
- [ ] ALL of org and related stuff
- [ ] LSP, ide, languages
- [ ] crdt
- [ ] eshell
- [ ] sudo edit
- [ ] hide dots
- [ ] misc programs
- [ ] lots and lots and lots more

* Notes to self:
