#+TITLE: Newmacs config
(placeholder name (i named it Newmacs because it's new unlike my old config))

/A modular Emacs distribution designed for speed, flexibility, transparency, and ease of configuration./

*  Why did I create this Emacs distribution?

I found that most popular Emacs distros like Doom Emacs are slow, bloated, and too abstracted away for my liking. I wanted to create an Emacs distribution that's very fast, minimal, and transparent, all the while meeting my needs and beyond.

Beyond me simply creating a personal Emacs config that does all of that, I wanted others, including those with very little Emacs experience, to pick up and use my config. I wanted users to be able to start off with a polished experience like that of Doom Emacs, then gradually strip away abstractions and uncessesary features to make it as minimal as desired, while still meeting all of their needs.

And to those who love having an environment that's as minimal and transparent as possible, instead of Emacs-distro-hopping to increasingly more minimal distros, your config can simply be flexibly molded into a more minimal one, all the way to something that's reminicient of vanilla Emacs.

*  The module system:

This distribution provides many modules, with each one providing a specific feature. The user has their own config file where they can load any of those modules, allowing one to easily put together a base config that meets their needs without introducing too much bloat.

- [[file:init.el][./init.el]] :: does miscellaneous initial setup, then loads the userside config.
- [[file:config.el][./config.el]] :: the userside config and is for declaring default fonts, loading your chosen modules, setting variables related to modules, and writing whatever elisp you want. You could try writing your own modules and load them from here, if you like.
- [[file:modules/][./modules/]] :: directory containing a list of directories from which modules will be loaded from. The default four directories are organized by how/when they are loaded.
  - [[file:modules/pre-init/][./modules/pre-init/]] :: directory containing modules that are run in [[file:init.el][init.el]], and must be run in a very specific order. These deal with package management and other pivotal features that must be configured first.
  - [[file:modules/init/][./modules/init/]] :: directory containing modules that are run in [[file:init.el][init.el]] after the modules in [[file:modules/pre-init/][pre-init/]], and can be run in any order, but some may be more preferable. These deal with themes and basic packages that are expected to be installed in many later modules.
  - [[file:modules/features/][./modules/features/]] :: directory containing lots of modules to be loaded from [[file:config.el][config.el]]. This is where you get to freely choose which modules to load. The order does not matter.

* Note:

This project is still very incomplete and under active (procrastinative) development.

* Installation

To use this config without eradicating your pre-existing =~/.emacs.d=, you may git clone the project anywhere, and then run =$ emacs --init-directory <path-to-repo>= to run emacs from that directory. 
Because meow with dvorak-programmer is the default, run the previous command with the argument =--sane-keybinds= to load qwerty meow keybinds.

All this is subject to change.

* Configuration

You can configure which modules are loaded in =config.el=. However, I wouldn't advise configuring it and expecting everything to work when you next run git pull. Use at your own risk!!!

* Basic keybinds reference (wip) (might not work based on modules loaded):

- M-o :: other-window
- SPC :: Meow/Evil leader key (if Meow, =SPC= is basically same as =C-c=)
- SPC f :: (prefix) files
- SPC b :: (prefix) buffers
- SPC w :: (prefix) windows (TO FIX)

* TODO:
- [ ] able to swap between evil and meow
- [ ] try to make compatible with at least dvp and qwerty
- [ ] evil-mode
- [ ] undo-tree
- [ ] crux
- [ ] free-keys
- [ ] better window management
- [ ] ivy config
- [ ] better ivy
- [ ] info
- [ ] darkroom
- [ ] calc
- [ ] dired/dirvish improve keybinds
- [ ] improve keybinds for everything
- [ ] stumpwm
- [ ] ALL of org and related stuff
- [ ] LSP, ide, languages
- [ ] crdt
- [ ] eshell
- [ ] sudo edit
- [ ] hide dots
- [ ] misc programs
- [ ] lots and lots and lots more

* Notes to self:

(override-module 'ri-meow-gen)
;; module not found
;; run before load modules?

have cursor pre-indented to header body distance in org-mode? is this bad? slow?
when open new help window, make it auto switch?
- actually, only has this effect if cursor at end of file/buffer...

For each user module found, create a function called mod/file-name that can be run to load the module!

Make C-<return> take the C-j command for lsp-mode? using [brackets] thing used in helpful mode?

For crux, make it local to buffer, like in org-mode only...

In userside config, =(:ri-disable)= will prevent future setup declaration with same name from running.

docview disable line numbers mode

docview disable blink cursor modee

TODO: create backup bitmap fontface for symbols? tamzen-powerline?

TODO: in stumpwm, startup emacsclient with cmd multi-vterm instance?
: emacsclient -ce "(multi-vterm)" -a "alacritty"

TODO: in stumpwm, for scratchpad terminal, run emacsclient with standard vterm?
: emacsclient -ce "(vterm)" -a "emacs"
do i need to do ~-a "emacs -e '(vterm)'"~ to work?
